import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast'
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jetbrains',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key="{process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${jetbrainsMono.variable} font-mono`}>
        <Toaster position='top-right' />
        {children}
      </body>
    </html>
  );
}
